!!F77-INC*******************************************************
!
!!Description: Include file for initializing thresholds used in
!               the spatial variability subroutine
!
!!Revision History:
!
!!Team-unique Header:
!
!!References and Credits:
! See Cloud Mask ATBD-MOD-06.
!
!!Design Notes:
!
!!END******************************************************

! ... Day time ocean spatial variability threshold

      real dovar11(1)

      common /dovar_thresholds/ dovar11
