!!F77-INC*******************************************************
!
!!Description: Include file for initializing thresholds used in
!               the coast and shallow ocean ndvi tests.
!
!!Revision History:
!
!!Team-unique Header:
!
!!References and Credits:
! See Cloud Mask ATBD-MOD-35.
!
!!Design Notes:
!
!!END******************************************************

! ... Coast and shallow ocean NDVI test thresholds

      real swc_ndvi(2)

      common /swc_ndvi_thresholds/ swc_ndvi
